name: Deploy
on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: ghcr.io/monalizaoverdrivee/unmannered-bot/unmannered-bot:prod
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  BOT_TOKEN: ${{ secrets.TOKEN }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  HOST: ${{ secrets.HOST }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Login in registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build container
        run: |
          docker-compose build --build-arg BOT_TOKEN=$BOT_TOKEN
      - name: Push image
        run: |
          docker-compose push
      - name: Set SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.SSH_KEY }}
          known_hosts: ${{ env.HOST }}
      - name: scan ssh
        run: ssh-keyscan -H ${{ env.HOST }} >> ~/.ssh/known_hosts
      - name: rsync
        run: rsync docker-compose.yml root@${{ env.HOST }}:/home/unmannered-bot/
      - name: LS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: root
        script: |
          cd /home
          ls -l
