name: Deploy
on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: ghcr.io/monalizaoverdrivee/unmannered-bot/unmannered-bot:prod
  DOCKER_USERNAME: ${{ secrets.DOCKER_ }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Login in registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build container
        run: |
          docker build -t $IMAGE_NAME
      - name: Push image
        run: |
          docker push $IMAGE_NAME
